# Generated by Django 5.0.4 on 2024-04-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
